version: '3'
# yaml file is configuration settings for all of the services that make up our  project
#
# what is docker compose ->a Tool that allows us to run our Docker image easily from our project location.

# now we need one service
services:
  app:
    build:
      context: . # this means root directory
    ports:
      - '8000:8000'
    volumes: # allows to update our image into our docker image in real time -=> 변경사항이 있으면 자동으로 업데이트 된다는 뜻 (in real time)
      - ./app:/app
    command: > # for line change use that 'greater' mark
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # shell command : python ---- available to run all IP(0.0.0.0)

    # dat dot is our current directory

# were going to have a service called app and thd build section of the configuration

# terminal > docker-compose build
# build our image using the Docker Compose configuration

# terminal > docker-compose run app sh -c "django-admin.py startproject app ."
# 이렇게하면, 최상단 app file 아래에 app folder와 manage.py

# git add .
# git commit -a
# message 쓰고, ese + :wq 로 빠져나온다
